from __future__ import annotations

from pathlib import Path

from .models import ZoneTerrain


def _lua_value(value):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "{" + ", ".join(_lua_value(v) for v in value) + "}"
    if isinstance(value, dict):
        parts = []
        for k, v in value.items():
            parts.append(f"{k} = {_lua_value(v)}")
        return "{" + ", ".join(parts) + "}"
    raise TypeError(f"Unsupported Lua conversion type: {type(value)!r}")


def write_zone_lua(path: Path, zone: ZoneTerrain, table_name: str = "TextAdventurerTerrainData") -> None:
    # WoW Classic Lua can overflow constant tables when huge literals are emitted in one chunk.
    # Emit terrain rows in batched builder functions so constants are split across functions.
    chunk_batch_size = 250
    marker_batch_size = 1000

    lines: list[str] = []
    lines.append("-- Auto-generated by tools/terrain_compiler. Do not edit by hand.")
    lines.append(f"{table_name} = {{")
    lines.append(f"  zoneKey = {_lua_value(zone.zone_key)},")
    lines.append(f"  mapName = {_lua_value(zone.map_name)},")
    lines.append(f"  mapBounds = {_lua_value(zone.map_bounds)},")
    lines.append(f"  tilesPresent = {_lua_value(zone.tiles_present)},")
    lines.append("  chunks = {},")
    lines.append("  markers = {},")
    lines.append("}")
    lines.append("")

    lines.append(f"local __ta_chunks = {table_name}.chunks")
    lines.append(f"local __ta_markers = {table_name}.markers")
    lines.append("")

    for batch_start in range(0, len(zone.chunks), chunk_batch_size):
        batch_end = min(batch_start + chunk_batch_size, len(zone.chunks))
        fn_index = batch_start // chunk_batch_size + 1
        lines.append(f"local function __ta_add_chunks_{fn_index}()")
        for c in zone.chunks[batch_start:batch_end]:
            lines.append("  __ta_chunks[#__ta_chunks + 1] = {")
            lines.append(f"    tile = {_lua_value([c.tile_x, c.tile_y])},")
            lines.append(f"    chunk = {_lua_value([c.chunk_x, c.chunk_y])},")
            lines.append(f"    world = {_lua_value([c.world_x, c.world_y, c.world_z])},")
            lines.append(f"    heights = {_lua_value(c.sampled_heights)},")
            lines.append(f"    slope = {_lua_value(c.sampled_slope)},")
            lines.append(f"    hasWater = {_lua_value(c.has_water)},")
            lines.append(f"    waterLevel = {_lua_value(c.water_level)},")
            lines.append(f"    texture = {_lua_value(c.texture_label)},")
            lines.append("  }")
        lines.append("end")
        lines.append(f"__ta_add_chunks_{fn_index}()")
        lines.append(f"__ta_add_chunks_{fn_index} = nil")
        lines.append("")

    for batch_start in range(0, len(zone.markers), marker_batch_size):
        batch_end = min(batch_start + marker_batch_size, len(zone.markers))
        fn_index = batch_start // marker_batch_size + 1
        lines.append(f"local function __ta_add_markers_{fn_index}()")
        for m in zone.markers[batch_start:batch_end]:
            lines.append("  __ta_markers[#__ta_markers + 1] = {")
            lines.append(f"    kind = {_lua_value(m.kind)},")
            lines.append(f"    id = {_lua_value(m.id)},")
            lines.append(f"    pos = {_lua_value([m.x, m.y, m.z])},")
            lines.append("  }")
        lines.append("end")
        lines.append(f"__ta_add_markers_{fn_index}()")
        lines.append(f"__ta_add_markers_{fn_index} = nil")
        lines.append("")

    lines.append("__ta_chunks = nil")
    lines.append("__ta_markers = nil")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
