from __future__ import annotations

from pathlib import Path

from .models import ZoneTerrain


def _lua_value(value):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "{" + ", ".join(_lua_value(v) for v in value) + "}"
    if isinstance(value, dict):
        parts = []
        for k, v in value.items():
            parts.append(f"{k} = {_lua_value(v)}")
        return "{" + ", ".join(parts) + "}"
    raise TypeError(f"Unsupported Lua conversion type: {type(value)!r}")


def write_zone_lua(path: Path, zone: ZoneTerrain, table_name: str = "TextAdventurerTerrainData") -> None:
    lines: list[str] = []
    lines.append("-- Auto-generated by tools/terrain_compiler. Do not edit by hand.")
    lines.append(f"{table_name} = {{")
    lines.append(f"  zoneKey = {_lua_value(zone.zone_key)},")
    lines.append(f"  mapName = {_lua_value(zone.map_name)},")
    lines.append(f"  mapBounds = {_lua_value(zone.map_bounds)},")
    lines.append(f"  tilesPresent = {_lua_value(zone.tiles_present)},")

    lines.append("  chunks = {")
    for c in zone.chunks:
        lines.append("    {")
        lines.append(f"      tile = {_lua_value([c.tile_x, c.tile_y])},")
        lines.append(f"      chunk = {_lua_value([c.chunk_x, c.chunk_y])},")
        lines.append(f"      world = {_lua_value([c.world_x, c.world_y, c.world_z])},")
        lines.append(f"      heights = {_lua_value(c.sampled_heights)},")
        lines.append(f"      slope = {_lua_value(c.sampled_slope)},")
        lines.append(f"      hasWater = {_lua_value(c.has_water)},")
        lines.append(f"      waterLevel = {_lua_value(c.water_level)},")
        lines.append(f"      texture = {_lua_value(c.texture_label)},")
        lines.append("    },")
    lines.append("  },")

    lines.append("  markers = {")
    for m in zone.markers:
        lines.append("    {")
        lines.append(f"      kind = {_lua_value(m.kind)},")
        lines.append(f"      id = {_lua_value(m.id)},")
        lines.append(f"      pos = {_lua_value([m.x, m.y, m.z])},")
        lines.append("    },")
    lines.append("  },")
    lines.append("}")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
